# Configuration for inference on SE(3) diffusion experiments.
defaults:
  - base
  - _self_
  - paths

inference:

  inference_dir: ${paths.inference_dir}

  # Use this to write with date-time stamp.
  name: run_${now:%Y-%m-%d}_${now:%H-%M}
  seed: 123
  task: null
  output_dir: inference_outputs/

  # Choose checkpoint path
  ckpt_path: ${paths.ckpt_dir}/last.ckpt

  use_gpu: True
  num_gpus: 1
  num_samples: 1

  interpolant:
    min_t: ${interpolant.min_t}
    rots:
      corrupt: True
      sample_schedule: exp
      exp_rate: 10
    trans:
      corrupt: True
      sample_schedule: linear
    cell:
      corrupt: True
    lattice:
      corrupt: True
      lognormal:
        loc: ${lattice.lognormal.loc}
        scale: ${lattice.lognormal.scale}
      uniform:
        low: 60.0
        high: 120.0
        eps: 0.1
    sampling:
      num_timesteps: 50
    self_condition: True

    twisting:
      use: False
      t_min: 0.2
      scale: 1.
      # scale_w_t: ot
      r_t: 1
      potential_trans: True
      potential_rot: True
      update_trans: True
      update_rot: True
      max_rot_grad_norm: 1000
      align: True
      motif_loc: False
      max_offsets: 1000
      # num_rots: 100
      num_rots: 1
      # scale_rots: math.inf
      scale_rots: 0.
      # scale_rots: 0.1
      obs_noise: 0.

